### ISSUE TITLE
Incorrect test: TestSquare

### ISSUE THREAD

**Issue by sxha092024** [JorgenMJobloop/CS-ASSIGNMENT_BUILDER-Backend-main-ver-1#1]
Code:
https://github.com/JorgenMJobloop/CS-ASSIGNMENT_BUILDER-Backend-main-ver-1/blob/e6975f07b87b34c8ac0d1af73e50e3c7ef14a9e0/Assignment/TestMethods.cs#L245-L253
Incorrect indexing leads to:
`Assert.Equal(16, Square(2))`, `Assert.Equal(25, Square(3))`, `Assert.Equal(64, Square(4))`.

Fix: rewrite test.

Suggested:
```cs
    [Assignment(11)]
    public void TestSquare()
    {
        for (int i = 2; i < 100; i++)
        {
            Assert.Equal(Double.Pow(i,2), Square(i));
        }
    }
```

**Comment by JorgenMJobloop** [comment]
Fix implemented
